# Generated by Django 5.1 on 2024-08-23 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="unit",
            new_name="measurement_unit",
        ),
    ]
