# Generated by Django 5.1 on 2024-08-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_measurement_unit_ingredient_unit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="unit",
            new_name="measurement_unit",
        ),
    ]
